### ISSUE TITLE
真的是刚需 

### ISSUE THREAD

**Issue by Yunnathai** [1556173267/react-native-get-channel#1]
真的是刚需  感谢作者 你的两个插件能解决我的燃眉之急。

一个获取渠道 一个安装应用。。。

**Comment by 1556173267** [comment]
谢谢认同。我在react-native-apk-manager这个插件里又加了几个实用方法，明天上传，喜欢的话帮忙star一下哦。 @jamninetyfive

**Comment by Yunnathai** [comment]
已star 已 follow 
请问下作者你对于封装 SDK拿手吗，
我们最近有个需求 需要接入广告SDK
但是看了下百度联盟 广点通都不支持react-native 
所以想在封装SDK方面学习点经验或者技巧。

**Comment by 1556173267** [comment]
说不上拿手。但是鼓捣鼓捣还是能封装出来的。我一开始也都不会。都是看别人的封装代码，自己学来用的。😂

**Comment by Yunnathai** [comment]
能否试试封装百度联盟的SDK
目前网上没人封装过，我认为还是有很大的需求的。
给你打call，可以有支付宝码请你喝2杯超大杯星爸爸。

**Comment by 1556173267** [comment]
好的。我这几天研究一下。

**Comment by Yunnathai** [comment]
好的 非常感谢。我把他们的sdk以及文档上传了。
[安卓SDK以及文档](www.mp4ba.hk/BaiduMobAds_MSSP_bd_SDK_android_v5.7.zip)
[IOSsdk以及文档](www.mp4ba.hk/BaiduMobAds_MSSP_bd_SDK_iOS_v4.5.zip)

**Comment by 1556173267** [comment]
@jamninetyfive 你好，你上传的地址有问题。请重新上传一下。

**Comment by Yunnathai** [comment]
> @jamninetyfive 你好，你上传的地址有问题。请重新上传一下。

挂微云了～  https://share.weiyun.com/5mugE1W

**Comment by 1556173267** [comment]
朋友我可能搞不了百度联盟这个东西了。使用流程实在是太复杂了。而且必须要企业用户才用，我注册完要我填写企业信息。我随便填完，又告诉我没有权限。 @jamninetyfive

**Comment by Yunnathai** [comment]
好的 我让同事搞好企业用户给你试试。

**Comment by 1556173267** [comment]
好的。

**Comment by Yunnathai** [comment]
> 好的。

哈喽 我来啦 不好意思 前段时间忙忘了 广点通SDK的可以帮忙封装看看吗？
谢谢。如果有时间的话 留个qq我加你给你账号密码。～
